// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: VisualBukkitRPC.proto

// Protobuf Java Version: 3.25.1
package com.gmail.visualbukkit.rpc;

public final class VisualBukkitRPC {
  private VisualBukkitRPC() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface ResponseOrBuilder extends
      // @@protoc_insertion_point(interface_extends:Response)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>optional string message = 1;</code>
     * @return Whether the message field is set.
     */
    boolean hasMessage();
    /**
     * <code>optional string message = 1;</code>
     * @return The message.
     */
    java.lang.String getMessage();
    /**
     * <code>optional string message = 1;</code>
     * @return The bytes for message.
     */
    com.google.protobuf.ByteString
        getMessageBytes();
  }
  /**
   * Protobuf type {@code Response}
   */
  public static final class Response extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:Response)
      ResponseOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use Response.newBuilder() to construct.
    private Response(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private Response() {
      message_ = "";
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new Response();
    }

    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.gmail.visualbukkit.rpc.VisualBukkitRPC.internal_static_Response_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.gmail.visualbukkit.rpc.VisualBukkitRPC.internal_static_Response_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.gmail.visualbukkit.rpc.VisualBukkitRPC.Response.class, com.gmail.visualbukkit.rpc.VisualBukkitRPC.Response.Builder.class);
    }

    private int bitField0_;
    public static final int MESSAGE_FIELD_NUMBER = 1;
    @SuppressWarnings("serial")
    private volatile java.lang.Object message_ = "";
    /**
     * <code>optional string message = 1;</code>
     * @return Whether the message field is set.
     */
    @java.lang.Override
    public boolean hasMessage() {
      return ((bitField0_ & 0x00000001) != 0);
    }
    /**
     * <code>optional string message = 1;</code>
     * @return The message.
     */
    @java.lang.Override
    public java.lang.String getMessage() {
      java.lang.Object ref = message_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        message_ = s;
        return s;
      }
    }
    /**
     * <code>optional string message = 1;</code>
     * @return The bytes for message.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getMessageBytes() {
      java.lang.Object ref = message_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        message_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (((bitField0_ & 0x00000001) != 0)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, message_);
      }
      getUnknownFields().writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) != 0)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, message_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.gmail.visualbukkit.rpc.VisualBukkitRPC.Response)) {
        return super.equals(obj);
      }
      com.gmail.visualbukkit.rpc.VisualBukkitRPC.Response other = (com.gmail.visualbukkit.rpc.VisualBukkitRPC.Response) obj;

      if (hasMessage() != other.hasMessage()) return false;
      if (hasMessage()) {
        if (!getMessage()
            .equals(other.getMessage())) return false;
      }
      if (!getUnknownFields().equals(other.getUnknownFields())) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (hasMessage()) {
        hash = (37 * hash) + MESSAGE_FIELD_NUMBER;
        hash = (53 * hash) + getMessage().hashCode();
      }
      hash = (29 * hash) + getUnknownFields().hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.gmail.visualbukkit.rpc.VisualBukkitRPC.Response parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.gmail.visualbukkit.rpc.VisualBukkitRPC.Response parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.gmail.visualbukkit.rpc.VisualBukkitRPC.Response parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.gmail.visualbukkit.rpc.VisualBukkitRPC.Response parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.gmail.visualbukkit.rpc.VisualBukkitRPC.Response parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.gmail.visualbukkit.rpc.VisualBukkitRPC.Response parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.gmail.visualbukkit.rpc.VisualBukkitRPC.Response parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.gmail.visualbukkit.rpc.VisualBukkitRPC.Response parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public static com.gmail.visualbukkit.rpc.VisualBukkitRPC.Response parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }

    public static com.gmail.visualbukkit.rpc.VisualBukkitRPC.Response parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.gmail.visualbukkit.rpc.VisualBukkitRPC.Response parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.gmail.visualbukkit.rpc.VisualBukkitRPC.Response parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.gmail.visualbukkit.rpc.VisualBukkitRPC.Response prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code Response}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:Response)
        com.gmail.visualbukkit.rpc.VisualBukkitRPC.ResponseOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.gmail.visualbukkit.rpc.VisualBukkitRPC.internal_static_Response_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.gmail.visualbukkit.rpc.VisualBukkitRPC.internal_static_Response_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.gmail.visualbukkit.rpc.VisualBukkitRPC.Response.class, com.gmail.visualbukkit.rpc.VisualBukkitRPC.Response.Builder.class);
      }

      // Construct using com.gmail.visualbukkit.rpc.VisualBukkitRPC.Response.newBuilder()
      private Builder() {

      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);

      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        bitField0_ = 0;
        message_ = "";
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.gmail.visualbukkit.rpc.VisualBukkitRPC.internal_static_Response_descriptor;
      }

      @java.lang.Override
      public com.gmail.visualbukkit.rpc.VisualBukkitRPC.Response getDefaultInstanceForType() {
        return com.gmail.visualbukkit.rpc.VisualBukkitRPC.Response.getDefaultInstance();
      }

      @java.lang.Override
      public com.gmail.visualbukkit.rpc.VisualBukkitRPC.Response build() {
        com.gmail.visualbukkit.rpc.VisualBukkitRPC.Response result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public com.gmail.visualbukkit.rpc.VisualBukkitRPC.Response buildPartial() {
        com.gmail.visualbukkit.rpc.VisualBukkitRPC.Response result = new com.gmail.visualbukkit.rpc.VisualBukkitRPC.Response(this);
        if (bitField0_ != 0) { buildPartial0(result); }
        onBuilt();
        return result;
      }

      private void buildPartial0(com.gmail.visualbukkit.rpc.VisualBukkitRPC.Response result) {
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) != 0)) {
          result.message_ = message_;
          to_bitField0_ |= 0x00000001;
        }
        result.bitField0_ |= to_bitField0_;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.gmail.visualbukkit.rpc.VisualBukkitRPC.Response) {
          return mergeFrom((com.gmail.visualbukkit.rpc.VisualBukkitRPC.Response)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.gmail.visualbukkit.rpc.VisualBukkitRPC.Response other) {
        if (other == com.gmail.visualbukkit.rpc.VisualBukkitRPC.Response.getDefaultInstance()) return this;
        if (other.hasMessage()) {
          message_ = other.message_;
          bitField0_ |= 0x00000001;
          onChanged();
        }
        this.mergeUnknownFields(other.getUnknownFields());
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        if (extensionRegistry == null) {
          throw new java.lang.NullPointerException();
        }
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              case 10: {
                message_ = input.readStringRequireUtf8();
                bitField0_ |= 0x00000001;
                break;
              } // case 10
              default: {
                if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                  done = true; // was an endgroup tag
                }
                break;
              } // default:
            } // switch (tag)
          } // while (!done)
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.unwrapIOException();
        } finally {
          onChanged();
        } // finally
        return this;
      }
      private int bitField0_;

      private java.lang.Object message_ = "";
      /**
       * <code>optional string message = 1;</code>
       * @return Whether the message field is set.
       */
      public boolean hasMessage() {
        return ((bitField0_ & 0x00000001) != 0);
      }
      /**
       * <code>optional string message = 1;</code>
       * @return The message.
       */
      public java.lang.String getMessage() {
        java.lang.Object ref = message_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          message_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string message = 1;</code>
       * @return The bytes for message.
       */
      public com.google.protobuf.ByteString
          getMessageBytes() {
        java.lang.Object ref = message_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          message_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string message = 1;</code>
       * @param value The message to set.
       * @return This builder for chaining.
       */
      public Builder setMessage(
          java.lang.String value) {
        if (value == null) { throw new NullPointerException(); }
        message_ = value;
        bitField0_ |= 0x00000001;
        onChanged();
        return this;
      }
      /**
       * <code>optional string message = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearMessage() {
        message_ = getDefaultInstance().getMessage();
        bitField0_ = (bitField0_ & ~0x00000001);
        onChanged();
        return this;
      }
      /**
       * <code>optional string message = 1;</code>
       * @param value The bytes for message to set.
       * @return This builder for chaining.
       */
      public Builder setMessageBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) { throw new NullPointerException(); }
        checkByteStringIsUtf8(value);
        message_ = value;
        bitField0_ |= 0x00000001;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:Response)
    }

    // @@protoc_insertion_point(class_scope:Response)
    private static final com.gmail.visualbukkit.rpc.VisualBukkitRPC.Response DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.gmail.visualbukkit.rpc.VisualBukkitRPC.Response();
    }

    public static com.gmail.visualbukkit.rpc.VisualBukkitRPC.Response getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<Response>
        PARSER = new com.google.protobuf.AbstractParser<Response>() {
      @java.lang.Override
      public Response parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        Builder builder = newBuilder();
        try {
          builder.mergeFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(builder.buildPartial());
        } catch (com.google.protobuf.UninitializedMessageException e) {
          throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(e)
              .setUnfinishedMessage(builder.buildPartial());
        }
        return builder.buildPartial();
      }
    };

    public static com.google.protobuf.Parser<Response> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<Response> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public com.gmail.visualbukkit.rpc.VisualBukkitRPC.Response getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface PingRequestOrBuilder extends
      // @@protoc_insertion_point(interface_extends:PingRequest)
      com.google.protobuf.MessageOrBuilder {
  }
  /**
   * Protobuf type {@code PingRequest}
   */
  public static final class PingRequest extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:PingRequest)
      PingRequestOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use PingRequest.newBuilder() to construct.
    private PingRequest(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private PingRequest() {
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new PingRequest();
    }

    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.gmail.visualbukkit.rpc.VisualBukkitRPC.internal_static_PingRequest_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.gmail.visualbukkit.rpc.VisualBukkitRPC.internal_static_PingRequest_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.gmail.visualbukkit.rpc.VisualBukkitRPC.PingRequest.class, com.gmail.visualbukkit.rpc.VisualBukkitRPC.PingRequest.Builder.class);
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getUnknownFields().writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      size += getUnknownFields().getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.gmail.visualbukkit.rpc.VisualBukkitRPC.PingRequest)) {
        return super.equals(obj);
      }
      com.gmail.visualbukkit.rpc.VisualBukkitRPC.PingRequest other = (com.gmail.visualbukkit.rpc.VisualBukkitRPC.PingRequest) obj;

      if (!getUnknownFields().equals(other.getUnknownFields())) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (29 * hash) + getUnknownFields().hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.gmail.visualbukkit.rpc.VisualBukkitRPC.PingRequest parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.gmail.visualbukkit.rpc.VisualBukkitRPC.PingRequest parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.gmail.visualbukkit.rpc.VisualBukkitRPC.PingRequest parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.gmail.visualbukkit.rpc.VisualBukkitRPC.PingRequest parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.gmail.visualbukkit.rpc.VisualBukkitRPC.PingRequest parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.gmail.visualbukkit.rpc.VisualBukkitRPC.PingRequest parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.gmail.visualbukkit.rpc.VisualBukkitRPC.PingRequest parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.gmail.visualbukkit.rpc.VisualBukkitRPC.PingRequest parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public static com.gmail.visualbukkit.rpc.VisualBukkitRPC.PingRequest parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }

    public static com.gmail.visualbukkit.rpc.VisualBukkitRPC.PingRequest parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.gmail.visualbukkit.rpc.VisualBukkitRPC.PingRequest parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.gmail.visualbukkit.rpc.VisualBukkitRPC.PingRequest parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.gmail.visualbukkit.rpc.VisualBukkitRPC.PingRequest prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code PingRequest}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:PingRequest)
        com.gmail.visualbukkit.rpc.VisualBukkitRPC.PingRequestOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.gmail.visualbukkit.rpc.VisualBukkitRPC.internal_static_PingRequest_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.gmail.visualbukkit.rpc.VisualBukkitRPC.internal_static_PingRequest_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.gmail.visualbukkit.rpc.VisualBukkitRPC.PingRequest.class, com.gmail.visualbukkit.rpc.VisualBukkitRPC.PingRequest.Builder.class);
      }

      // Construct using com.gmail.visualbukkit.rpc.VisualBukkitRPC.PingRequest.newBuilder()
      private Builder() {

      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);

      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.gmail.visualbukkit.rpc.VisualBukkitRPC.internal_static_PingRequest_descriptor;
      }

      @java.lang.Override
      public com.gmail.visualbukkit.rpc.VisualBukkitRPC.PingRequest getDefaultInstanceForType() {
        return com.gmail.visualbukkit.rpc.VisualBukkitRPC.PingRequest.getDefaultInstance();
      }

      @java.lang.Override
      public com.gmail.visualbukkit.rpc.VisualBukkitRPC.PingRequest build() {
        com.gmail.visualbukkit.rpc.VisualBukkitRPC.PingRequest result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public com.gmail.visualbukkit.rpc.VisualBukkitRPC.PingRequest buildPartial() {
        com.gmail.visualbukkit.rpc.VisualBukkitRPC.PingRequest result = new com.gmail.visualbukkit.rpc.VisualBukkitRPC.PingRequest(this);
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.gmail.visualbukkit.rpc.VisualBukkitRPC.PingRequest) {
          return mergeFrom((com.gmail.visualbukkit.rpc.VisualBukkitRPC.PingRequest)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.gmail.visualbukkit.rpc.VisualBukkitRPC.PingRequest other) {
        if (other == com.gmail.visualbukkit.rpc.VisualBukkitRPC.PingRequest.getDefaultInstance()) return this;
        this.mergeUnknownFields(other.getUnknownFields());
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        if (extensionRegistry == null) {
          throw new java.lang.NullPointerException();
        }
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              default: {
                if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                  done = true; // was an endgroup tag
                }
                break;
              } // default:
            } // switch (tag)
          } // while (!done)
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.unwrapIOException();
        } finally {
          onChanged();
        } // finally
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:PingRequest)
    }

    // @@protoc_insertion_point(class_scope:PingRequest)
    private static final com.gmail.visualbukkit.rpc.VisualBukkitRPC.PingRequest DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.gmail.visualbukkit.rpc.VisualBukkitRPC.PingRequest();
    }

    public static com.gmail.visualbukkit.rpc.VisualBukkitRPC.PingRequest getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<PingRequest>
        PARSER = new com.google.protobuf.AbstractParser<PingRequest>() {
      @java.lang.Override
      public PingRequest parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        Builder builder = newBuilder();
        try {
          builder.mergeFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(builder.buildPartial());
        } catch (com.google.protobuf.UninitializedMessageException e) {
          throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(e)
              .setUnfinishedMessage(builder.buildPartial());
        }
        return builder.buildPartial();
      }
    };

    public static com.google.protobuf.Parser<PingRequest> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<PingRequest> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public com.gmail.visualbukkit.rpc.VisualBukkitRPC.PingRequest getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface ImportItemStackRequestOrBuilder extends
      // @@protoc_insertion_point(interface_extends:ImportItemStackRequest)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>string yaml = 1;</code>
     * @return The yaml.
     */
    java.lang.String getYaml();
    /**
     * <code>string yaml = 1;</code>
     * @return The bytes for yaml.
     */
    com.google.protobuf.ByteString
        getYamlBytes();
  }
  /**
   * Protobuf type {@code ImportItemStackRequest}
   */
  public static final class ImportItemStackRequest extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:ImportItemStackRequest)
      ImportItemStackRequestOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use ImportItemStackRequest.newBuilder() to construct.
    private ImportItemStackRequest(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private ImportItemStackRequest() {
      yaml_ = "";
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new ImportItemStackRequest();
    }

    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.gmail.visualbukkit.rpc.VisualBukkitRPC.internal_static_ImportItemStackRequest_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.gmail.visualbukkit.rpc.VisualBukkitRPC.internal_static_ImportItemStackRequest_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.gmail.visualbukkit.rpc.VisualBukkitRPC.ImportItemStackRequest.class, com.gmail.visualbukkit.rpc.VisualBukkitRPC.ImportItemStackRequest.Builder.class);
    }

    public static final int YAML_FIELD_NUMBER = 1;
    @SuppressWarnings("serial")
    private volatile java.lang.Object yaml_ = "";
    /**
     * <code>string yaml = 1;</code>
     * @return The yaml.
     */
    @java.lang.Override
    public java.lang.String getYaml() {
      java.lang.Object ref = yaml_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        yaml_ = s;
        return s;
      }
    }
    /**
     * <code>string yaml = 1;</code>
     * @return The bytes for yaml.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getYamlBytes() {
      java.lang.Object ref = yaml_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        yaml_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(yaml_)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, yaml_);
      }
      getUnknownFields().writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(yaml_)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, yaml_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.gmail.visualbukkit.rpc.VisualBukkitRPC.ImportItemStackRequest)) {
        return super.equals(obj);
      }
      com.gmail.visualbukkit.rpc.VisualBukkitRPC.ImportItemStackRequest other = (com.gmail.visualbukkit.rpc.VisualBukkitRPC.ImportItemStackRequest) obj;

      if (!getYaml()
          .equals(other.getYaml())) return false;
      if (!getUnknownFields().equals(other.getUnknownFields())) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + YAML_FIELD_NUMBER;
      hash = (53 * hash) + getYaml().hashCode();
      hash = (29 * hash) + getUnknownFields().hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.gmail.visualbukkit.rpc.VisualBukkitRPC.ImportItemStackRequest parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.gmail.visualbukkit.rpc.VisualBukkitRPC.ImportItemStackRequest parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.gmail.visualbukkit.rpc.VisualBukkitRPC.ImportItemStackRequest parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.gmail.visualbukkit.rpc.VisualBukkitRPC.ImportItemStackRequest parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.gmail.visualbukkit.rpc.VisualBukkitRPC.ImportItemStackRequest parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.gmail.visualbukkit.rpc.VisualBukkitRPC.ImportItemStackRequest parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.gmail.visualbukkit.rpc.VisualBukkitRPC.ImportItemStackRequest parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.gmail.visualbukkit.rpc.VisualBukkitRPC.ImportItemStackRequest parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public static com.gmail.visualbukkit.rpc.VisualBukkitRPC.ImportItemStackRequest parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }

    public static com.gmail.visualbukkit.rpc.VisualBukkitRPC.ImportItemStackRequest parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.gmail.visualbukkit.rpc.VisualBukkitRPC.ImportItemStackRequest parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.gmail.visualbukkit.rpc.VisualBukkitRPC.ImportItemStackRequest parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.gmail.visualbukkit.rpc.VisualBukkitRPC.ImportItemStackRequest prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code ImportItemStackRequest}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:ImportItemStackRequest)
        com.gmail.visualbukkit.rpc.VisualBukkitRPC.ImportItemStackRequestOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.gmail.visualbukkit.rpc.VisualBukkitRPC.internal_static_ImportItemStackRequest_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.gmail.visualbukkit.rpc.VisualBukkitRPC.internal_static_ImportItemStackRequest_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.gmail.visualbukkit.rpc.VisualBukkitRPC.ImportItemStackRequest.class, com.gmail.visualbukkit.rpc.VisualBukkitRPC.ImportItemStackRequest.Builder.class);
      }

      // Construct using com.gmail.visualbukkit.rpc.VisualBukkitRPC.ImportItemStackRequest.newBuilder()
      private Builder() {

      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);

      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        bitField0_ = 0;
        yaml_ = "";
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.gmail.visualbukkit.rpc.VisualBukkitRPC.internal_static_ImportItemStackRequest_descriptor;
      }

      @java.lang.Override
      public com.gmail.visualbukkit.rpc.VisualBukkitRPC.ImportItemStackRequest getDefaultInstanceForType() {
        return com.gmail.visualbukkit.rpc.VisualBukkitRPC.ImportItemStackRequest.getDefaultInstance();
      }

      @java.lang.Override
      public com.gmail.visualbukkit.rpc.VisualBukkitRPC.ImportItemStackRequest build() {
        com.gmail.visualbukkit.rpc.VisualBukkitRPC.ImportItemStackRequest result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public com.gmail.visualbukkit.rpc.VisualBukkitRPC.ImportItemStackRequest buildPartial() {
        com.gmail.visualbukkit.rpc.VisualBukkitRPC.ImportItemStackRequest result = new com.gmail.visualbukkit.rpc.VisualBukkitRPC.ImportItemStackRequest(this);
        if (bitField0_ != 0) { buildPartial0(result); }
        onBuilt();
        return result;
      }

      private void buildPartial0(com.gmail.visualbukkit.rpc.VisualBukkitRPC.ImportItemStackRequest result) {
        int from_bitField0_ = bitField0_;
        if (((from_bitField0_ & 0x00000001) != 0)) {
          result.yaml_ = yaml_;
        }
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.gmail.visualbukkit.rpc.VisualBukkitRPC.ImportItemStackRequest) {
          return mergeFrom((com.gmail.visualbukkit.rpc.VisualBukkitRPC.ImportItemStackRequest)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.gmail.visualbukkit.rpc.VisualBukkitRPC.ImportItemStackRequest other) {
        if (other == com.gmail.visualbukkit.rpc.VisualBukkitRPC.ImportItemStackRequest.getDefaultInstance()) return this;
        if (!other.getYaml().isEmpty()) {
          yaml_ = other.yaml_;
          bitField0_ |= 0x00000001;
          onChanged();
        }
        this.mergeUnknownFields(other.getUnknownFields());
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        if (extensionRegistry == null) {
          throw new java.lang.NullPointerException();
        }
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              case 10: {
                yaml_ = input.readStringRequireUtf8();
                bitField0_ |= 0x00000001;
                break;
              } // case 10
              default: {
                if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                  done = true; // was an endgroup tag
                }
                break;
              } // default:
            } // switch (tag)
          } // while (!done)
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.unwrapIOException();
        } finally {
          onChanged();
        } // finally
        return this;
      }
      private int bitField0_;

      private java.lang.Object yaml_ = "";
      /**
       * <code>string yaml = 1;</code>
       * @return The yaml.
       */
      public java.lang.String getYaml() {
        java.lang.Object ref = yaml_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          yaml_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string yaml = 1;</code>
       * @return The bytes for yaml.
       */
      public com.google.protobuf.ByteString
          getYamlBytes() {
        java.lang.Object ref = yaml_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          yaml_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string yaml = 1;</code>
       * @param value The yaml to set.
       * @return This builder for chaining.
       */
      public Builder setYaml(
          java.lang.String value) {
        if (value == null) { throw new NullPointerException(); }
        yaml_ = value;
        bitField0_ |= 0x00000001;
        onChanged();
        return this;
      }
      /**
       * <code>string yaml = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearYaml() {
        yaml_ = getDefaultInstance().getYaml();
        bitField0_ = (bitField0_ & ~0x00000001);
        onChanged();
        return this;
      }
      /**
       * <code>string yaml = 1;</code>
       * @param value The bytes for yaml to set.
       * @return This builder for chaining.
       */
      public Builder setYamlBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) { throw new NullPointerException(); }
        checkByteStringIsUtf8(value);
        yaml_ = value;
        bitField0_ |= 0x00000001;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:ImportItemStackRequest)
    }

    // @@protoc_insertion_point(class_scope:ImportItemStackRequest)
    private static final com.gmail.visualbukkit.rpc.VisualBukkitRPC.ImportItemStackRequest DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.gmail.visualbukkit.rpc.VisualBukkitRPC.ImportItemStackRequest();
    }

    public static com.gmail.visualbukkit.rpc.VisualBukkitRPC.ImportItemStackRequest getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<ImportItemStackRequest>
        PARSER = new com.google.protobuf.AbstractParser<ImportItemStackRequest>() {
      @java.lang.Override
      public ImportItemStackRequest parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        Builder builder = newBuilder();
        try {
          builder.mergeFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(builder.buildPartial());
        } catch (com.google.protobuf.UninitializedMessageException e) {
          throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(e)
              .setUnfinishedMessage(builder.buildPartial());
        }
        return builder.buildPartial();
      }
    };

    public static com.google.protobuf.Parser<ImportItemStackRequest> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<ImportItemStackRequest> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public com.gmail.visualbukkit.rpc.VisualBukkitRPC.ImportItemStackRequest getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface ReportExceptionRequestOrBuilder extends
      // @@protoc_insertion_point(interface_extends:ReportExceptionRequest)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>string blockUUID = 1;</code>
     * @return The blockUUID.
     */
    java.lang.String getBlockUUID();
    /**
     * <code>string blockUUID = 1;</code>
     * @return The bytes for blockUUID.
     */
    com.google.protobuf.ByteString
        getBlockUUIDBytes();

    /**
     * <code>string stacktrace = 2;</code>
     * @return The stacktrace.
     */
    java.lang.String getStacktrace();
    /**
     * <code>string stacktrace = 2;</code>
     * @return The bytes for stacktrace.
     */
    com.google.protobuf.ByteString
        getStacktraceBytes();
  }
  /**
   * Protobuf type {@code ReportExceptionRequest}
   */
  public static final class ReportExceptionRequest extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:ReportExceptionRequest)
      ReportExceptionRequestOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use ReportExceptionRequest.newBuilder() to construct.
    private ReportExceptionRequest(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private ReportExceptionRequest() {
      blockUUID_ = "";
      stacktrace_ = "";
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new ReportExceptionRequest();
    }

    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.gmail.visualbukkit.rpc.VisualBukkitRPC.internal_static_ReportExceptionRequest_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.gmail.visualbukkit.rpc.VisualBukkitRPC.internal_static_ReportExceptionRequest_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.gmail.visualbukkit.rpc.VisualBukkitRPC.ReportExceptionRequest.class, com.gmail.visualbukkit.rpc.VisualBukkitRPC.ReportExceptionRequest.Builder.class);
    }

    public static final int BLOCKUUID_FIELD_NUMBER = 1;
    @SuppressWarnings("serial")
    private volatile java.lang.Object blockUUID_ = "";
    /**
     * <code>string blockUUID = 1;</code>
     * @return The blockUUID.
     */
    @java.lang.Override
    public java.lang.String getBlockUUID() {
      java.lang.Object ref = blockUUID_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        blockUUID_ = s;
        return s;
      }
    }
    /**
     * <code>string blockUUID = 1;</code>
     * @return The bytes for blockUUID.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getBlockUUIDBytes() {
      java.lang.Object ref = blockUUID_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        blockUUID_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int STACKTRACE_FIELD_NUMBER = 2;
    @SuppressWarnings("serial")
    private volatile java.lang.Object stacktrace_ = "";
    /**
     * <code>string stacktrace = 2;</code>
     * @return The stacktrace.
     */
    @java.lang.Override
    public java.lang.String getStacktrace() {
      java.lang.Object ref = stacktrace_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        stacktrace_ = s;
        return s;
      }
    }
    /**
     * <code>string stacktrace = 2;</code>
     * @return The bytes for stacktrace.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getStacktraceBytes() {
      java.lang.Object ref = stacktrace_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        stacktrace_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(blockUUID_)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, blockUUID_);
      }
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(stacktrace_)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, stacktrace_);
      }
      getUnknownFields().writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(blockUUID_)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, blockUUID_);
      }
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(stacktrace_)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, stacktrace_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.gmail.visualbukkit.rpc.VisualBukkitRPC.ReportExceptionRequest)) {
        return super.equals(obj);
      }
      com.gmail.visualbukkit.rpc.VisualBukkitRPC.ReportExceptionRequest other = (com.gmail.visualbukkit.rpc.VisualBukkitRPC.ReportExceptionRequest) obj;

      if (!getBlockUUID()
          .equals(other.getBlockUUID())) return false;
      if (!getStacktrace()
          .equals(other.getStacktrace())) return false;
      if (!getUnknownFields().equals(other.getUnknownFields())) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + BLOCKUUID_FIELD_NUMBER;
      hash = (53 * hash) + getBlockUUID().hashCode();
      hash = (37 * hash) + STACKTRACE_FIELD_NUMBER;
      hash = (53 * hash) + getStacktrace().hashCode();
      hash = (29 * hash) + getUnknownFields().hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.gmail.visualbukkit.rpc.VisualBukkitRPC.ReportExceptionRequest parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.gmail.visualbukkit.rpc.VisualBukkitRPC.ReportExceptionRequest parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.gmail.visualbukkit.rpc.VisualBukkitRPC.ReportExceptionRequest parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.gmail.visualbukkit.rpc.VisualBukkitRPC.ReportExceptionRequest parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.gmail.visualbukkit.rpc.VisualBukkitRPC.ReportExceptionRequest parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.gmail.visualbukkit.rpc.VisualBukkitRPC.ReportExceptionRequest parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.gmail.visualbukkit.rpc.VisualBukkitRPC.ReportExceptionRequest parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.gmail.visualbukkit.rpc.VisualBukkitRPC.ReportExceptionRequest parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public static com.gmail.visualbukkit.rpc.VisualBukkitRPC.ReportExceptionRequest parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }

    public static com.gmail.visualbukkit.rpc.VisualBukkitRPC.ReportExceptionRequest parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.gmail.visualbukkit.rpc.VisualBukkitRPC.ReportExceptionRequest parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.gmail.visualbukkit.rpc.VisualBukkitRPC.ReportExceptionRequest parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.gmail.visualbukkit.rpc.VisualBukkitRPC.ReportExceptionRequest prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code ReportExceptionRequest}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:ReportExceptionRequest)
        com.gmail.visualbukkit.rpc.VisualBukkitRPC.ReportExceptionRequestOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.gmail.visualbukkit.rpc.VisualBukkitRPC.internal_static_ReportExceptionRequest_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.gmail.visualbukkit.rpc.VisualBukkitRPC.internal_static_ReportExceptionRequest_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.gmail.visualbukkit.rpc.VisualBukkitRPC.ReportExceptionRequest.class, com.gmail.visualbukkit.rpc.VisualBukkitRPC.ReportExceptionRequest.Builder.class);
      }

      // Construct using com.gmail.visualbukkit.rpc.VisualBukkitRPC.ReportExceptionRequest.newBuilder()
      private Builder() {

      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);

      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        bitField0_ = 0;
        blockUUID_ = "";
        stacktrace_ = "";
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.gmail.visualbukkit.rpc.VisualBukkitRPC.internal_static_ReportExceptionRequest_descriptor;
      }

      @java.lang.Override
      public com.gmail.visualbukkit.rpc.VisualBukkitRPC.ReportExceptionRequest getDefaultInstanceForType() {
        return com.gmail.visualbukkit.rpc.VisualBukkitRPC.ReportExceptionRequest.getDefaultInstance();
      }

      @java.lang.Override
      public com.gmail.visualbukkit.rpc.VisualBukkitRPC.ReportExceptionRequest build() {
        com.gmail.visualbukkit.rpc.VisualBukkitRPC.ReportExceptionRequest result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public com.gmail.visualbukkit.rpc.VisualBukkitRPC.ReportExceptionRequest buildPartial() {
        com.gmail.visualbukkit.rpc.VisualBukkitRPC.ReportExceptionRequest result = new com.gmail.visualbukkit.rpc.VisualBukkitRPC.ReportExceptionRequest(this);
        if (bitField0_ != 0) { buildPartial0(result); }
        onBuilt();
        return result;
      }

      private void buildPartial0(com.gmail.visualbukkit.rpc.VisualBukkitRPC.ReportExceptionRequest result) {
        int from_bitField0_ = bitField0_;
        if (((from_bitField0_ & 0x00000001) != 0)) {
          result.blockUUID_ = blockUUID_;
        }
        if (((from_bitField0_ & 0x00000002) != 0)) {
          result.stacktrace_ = stacktrace_;
        }
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.gmail.visualbukkit.rpc.VisualBukkitRPC.ReportExceptionRequest) {
          return mergeFrom((com.gmail.visualbukkit.rpc.VisualBukkitRPC.ReportExceptionRequest)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.gmail.visualbukkit.rpc.VisualBukkitRPC.ReportExceptionRequest other) {
        if (other == com.gmail.visualbukkit.rpc.VisualBukkitRPC.ReportExceptionRequest.getDefaultInstance()) return this;
        if (!other.getBlockUUID().isEmpty()) {
          blockUUID_ = other.blockUUID_;
          bitField0_ |= 0x00000001;
          onChanged();
        }
        if (!other.getStacktrace().isEmpty()) {
          stacktrace_ = other.stacktrace_;
          bitField0_ |= 0x00000002;
          onChanged();
        }
        this.mergeUnknownFields(other.getUnknownFields());
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        if (extensionRegistry == null) {
          throw new java.lang.NullPointerException();
        }
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              case 10: {
                blockUUID_ = input.readStringRequireUtf8();
                bitField0_ |= 0x00000001;
                break;
              } // case 10
              case 18: {
                stacktrace_ = input.readStringRequireUtf8();
                bitField0_ |= 0x00000002;
                break;
              } // case 18
              default: {
                if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                  done = true; // was an endgroup tag
                }
                break;
              } // default:
            } // switch (tag)
          } // while (!done)
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.unwrapIOException();
        } finally {
          onChanged();
        } // finally
        return this;
      }
      private int bitField0_;

      private java.lang.Object blockUUID_ = "";
      /**
       * <code>string blockUUID = 1;</code>
       * @return The blockUUID.
       */
      public java.lang.String getBlockUUID() {
        java.lang.Object ref = blockUUID_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          blockUUID_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string blockUUID = 1;</code>
       * @return The bytes for blockUUID.
       */
      public com.google.protobuf.ByteString
          getBlockUUIDBytes() {
        java.lang.Object ref = blockUUID_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          blockUUID_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string blockUUID = 1;</code>
       * @param value The blockUUID to set.
       * @return This builder for chaining.
       */
      public Builder setBlockUUID(
          java.lang.String value) {
        if (value == null) { throw new NullPointerException(); }
        blockUUID_ = value;
        bitField0_ |= 0x00000001;
        onChanged();
        return this;
      }
      /**
       * <code>string blockUUID = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearBlockUUID() {
        blockUUID_ = getDefaultInstance().getBlockUUID();
        bitField0_ = (bitField0_ & ~0x00000001);
        onChanged();
        return this;
      }
      /**
       * <code>string blockUUID = 1;</code>
       * @param value The bytes for blockUUID to set.
       * @return This builder for chaining.
       */
      public Builder setBlockUUIDBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) { throw new NullPointerException(); }
        checkByteStringIsUtf8(value);
        blockUUID_ = value;
        bitField0_ |= 0x00000001;
        onChanged();
        return this;
      }

      private java.lang.Object stacktrace_ = "";
      /**
       * <code>string stacktrace = 2;</code>
       * @return The stacktrace.
       */
      public java.lang.String getStacktrace() {
        java.lang.Object ref = stacktrace_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          stacktrace_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string stacktrace = 2;</code>
       * @return The bytes for stacktrace.
       */
      public com.google.protobuf.ByteString
          getStacktraceBytes() {
        java.lang.Object ref = stacktrace_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          stacktrace_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string stacktrace = 2;</code>
       * @param value The stacktrace to set.
       * @return This builder for chaining.
       */
      public Builder setStacktrace(
          java.lang.String value) {
        if (value == null) { throw new NullPointerException(); }
        stacktrace_ = value;
        bitField0_ |= 0x00000002;
        onChanged();
        return this;
      }
      /**
       * <code>string stacktrace = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearStacktrace() {
        stacktrace_ = getDefaultInstance().getStacktrace();
        bitField0_ = (bitField0_ & ~0x00000002);
        onChanged();
        return this;
      }
      /**
       * <code>string stacktrace = 2;</code>
       * @param value The bytes for stacktrace to set.
       * @return This builder for chaining.
       */
      public Builder setStacktraceBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) { throw new NullPointerException(); }
        checkByteStringIsUtf8(value);
        stacktrace_ = value;
        bitField0_ |= 0x00000002;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:ReportExceptionRequest)
    }

    // @@protoc_insertion_point(class_scope:ReportExceptionRequest)
    private static final com.gmail.visualbukkit.rpc.VisualBukkitRPC.ReportExceptionRequest DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.gmail.visualbukkit.rpc.VisualBukkitRPC.ReportExceptionRequest();
    }

    public static com.gmail.visualbukkit.rpc.VisualBukkitRPC.ReportExceptionRequest getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<ReportExceptionRequest>
        PARSER = new com.google.protobuf.AbstractParser<ReportExceptionRequest>() {
      @java.lang.Override
      public ReportExceptionRequest parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        Builder builder = newBuilder();
        try {
          builder.mergeFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(builder.buildPartial());
        } catch (com.google.protobuf.UninitializedMessageException e) {
          throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(e)
              .setUnfinishedMessage(builder.buildPartial());
        }
        return builder.buildPartial();
      }
    };

    public static com.google.protobuf.Parser<ReportExceptionRequest> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<ReportExceptionRequest> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public com.gmail.visualbukkit.rpc.VisualBukkitRPC.ReportExceptionRequest getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Response_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Response_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_PingRequest_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_PingRequest_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_ImportItemStackRequest_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_ImportItemStackRequest_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_ReportExceptionRequest_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_ReportExceptionRequest_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\025VisualBukkitRPC.proto\",\n\010Response\022\024\n\007m" +
      "essage\030\001 \001(\tH\000\210\001\001B\n\n\010_message\"\r\n\013PingReq" +
      "uest\"&\n\026ImportItemStackRequest\022\014\n\004yaml\030\001" +
      " \001(\t\"?\n\026ReportExceptionRequest\022\021\n\tblockU" +
      "UID\030\001 \001(\t\022\022\n\nstacktrace\030\002 \001(\t2\235\001\n\014Visual" +
      "Bukkit\022\037\n\004Ping\022\014.PingRequest\032\t.Response\022" +
      "5\n\017ImportItemStack\022\027.ImportItemStackRequ" +
      "est\032\t.Response\0225\n\017ReportException\022\027.Repo" +
      "rtExceptionRequest\032\t.ResponseB\034\n\032com.gma" +
      "il.visualbukkit.rpcb\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_Response_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_Response_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Response_descriptor,
        new java.lang.String[] { "Message", });
    internal_static_PingRequest_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_PingRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_PingRequest_descriptor,
        new java.lang.String[] { });
    internal_static_ImportItemStackRequest_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_ImportItemStackRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_ImportItemStackRequest_descriptor,
        new java.lang.String[] { "Yaml", });
    internal_static_ReportExceptionRequest_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_ReportExceptionRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_ReportExceptionRequest_descriptor,
        new java.lang.String[] { "BlockUUID", "Stacktrace", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
