package discord_game_sdk;
import com.sun.jna.Pointer;
import com.sun.jna.Structure;
import java.util.Arrays;
import java.util.List;
/**
 * <i>native declaration : discord_game_sdk.h:345</i><br>
 * This file was autogenerated by <a href="https://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="https://ochafik.com/">Olivier Chafik</a> that <a href="https://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="https://nativelibs4java.googlecode.com/">NativeLibs4Java</a> , <a href="https://rococoa.dev.java.net/">Rococoa</a>, or <a href="https://jna.dev.java.net/">JNA</a>.
 */
public class DiscordSkuPrice extends Structure {
	public int amount;
	/** C type : char[16] */
	public byte[] currency = new byte[16];
	public DiscordSkuPrice() {
		super();
	}
	protected List<String> getFieldOrder() {
		return Arrays.asList("amount", "currency");
	}
	/** @param currency C type : char[16] */
	public DiscordSkuPrice(int amount, byte currency[]) {
		super();
		this.amount = amount;
		if ((currency.length != this.currency.length)) 
			throw new IllegalArgumentException("Wrong array size !");
		this.currency = currency;
	}
	public DiscordSkuPrice(Pointer peer) {
		super(peer);
	}
	public static class ByReference extends DiscordSkuPrice implements Structure.ByReference {
		
	};
	public static class ByValue extends DiscordSkuPrice implements Structure.ByValue {
		
	};
}
