package discord_game_sdk;
import com.sun.jna.Pointer;
import com.sun.jna.Structure;
import java.util.Arrays;
import java.util.List;
/**
 * <i>native declaration : discord_game_sdk.h:244</i><br>
 * This file was autogenerated by <a href="https://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="https://ochafik.com/">Olivier Chafik</a> that <a href="https://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="https://nativelibs4java.googlecode.com/">NativeLibs4Java</a> , <a href="https://rococoa.dev.java.net/">Rococoa</a>, or <a href="https://jna.dev.java.net/">JNA</a>.
 */
public class DiscordImageHandle extends Structure {
	/**
	 * @see EDiscordImageType<br>
	 * C type : EDiscordImageType
	 */
	public int type;
	public long id;
	public int size;
	public DiscordImageHandle() {
		super();
	}
	protected List<String> getFieldOrder() {
		return Arrays.asList("type", "id", "size");
	}
	/**
	 * @param type @see EDiscordImageType<br>
	 * C type : EDiscordImageType
	 */
	public DiscordImageHandle(int type, long id, int size) {
		super();
		this.type = type;
		this.id = id;
		this.size = size;
	}
	public DiscordImageHandle(Pointer peer) {
		super(peer);
	}
	public static class ByReference extends DiscordImageHandle implements Structure.ByReference {
		
	};
	public static class ByValue extends DiscordImageHandle implements Structure.ByValue {
		
	};
}
