package discord_game_sdk;
import com.sun.jna.Pointer;
import com.sun.jna.Structure;
import java.util.Arrays;
import java.util.List;
/**
 * <i>native declaration : discord_game_sdk.h:255</i><br>
 * This file was autogenerated by <a href="https://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="https://ochafik.com/">Olivier Chafik</a> that <a href="https://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="https://nativelibs4java.googlecode.com/">NativeLibs4Java</a> , <a href="https://rococoa.dev.java.net/">Rococoa</a>, or <a href="https://jna.dev.java.net/">JNA</a>.
 */
public class DiscordActivityTimestamps extends Structure {
	/** C type : DiscordTimestamp */
	public long start;
	/** C type : DiscordTimestamp */
	public long end;
	public DiscordActivityTimestamps() {
		super();
	}
	protected List<String> getFieldOrder() {
		return Arrays.asList("start", "end");
	}
	/**
	 * @param start C type : DiscordTimestamp<br>
	 * @param end C type : DiscordTimestamp
	 */
	public DiscordActivityTimestamps(long start, long end) {
		super();
		this.start = start;
		this.end = end;
	}
	public DiscordActivityTimestamps(Pointer peer) {
		super(peer);
	}
	public static class ByReference extends DiscordActivityTimestamps implements Structure.ByReference {
		
	};
	public static class ByValue extends DiscordActivityTimestamps implements Structure.ByValue {
		
	};
}
