package discord_game_sdk;
import com.sun.jna.Pointer;
import com.sun.jna.Structure;
import java.util.Arrays;
import java.util.List;
/**
 * <i>native declaration : discord_game_sdk.h:318</i><br>
 * This file was autogenerated by <a href="https://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="https://ochafik.com/">Olivier Chafik</a> that <a href="https://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="https://nativelibs4java.googlecode.com/">NativeLibs4Java</a> , <a href="https://rococoa.dev.java.net/">Rococoa</a>, or <a href="https://jna.dev.java.net/">JNA</a>.
 */
public class DiscordImeUnderline extends Structure {
	public int from;
	public int to;
	public int color;
	public int background_color;
	public byte thick;
	public DiscordImeUnderline() {
		super();
	}
	protected List<String> getFieldOrder() {
		return Arrays.asList("from", "to", "color", "background_color", "thick");
	}
	public DiscordImeUnderline(int from, int to, int color, int background_color, byte thick) {
		super();
		this.from = from;
		this.to = to;
		this.color = color;
		this.background_color = background_color;
		this.thick = thick;
	}
	public DiscordImeUnderline(Pointer peer) {
		super(peer);
	}
	public static class ByReference extends DiscordImeUnderline implements Structure.ByReference {
		
	};
	public static class ByValue extends DiscordImeUnderline implements Structure.ByValue {
		
	};
}
