package discord_game_sdk;
import com.sun.jna.Pointer;
import com.sun.jna.Structure;
import java.util.Arrays;
import java.util.List;
/**
 * <i>native declaration : discord_game_sdk.h:230</i><br>
 * This file was autogenerated by <a href="https://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="https://ochafik.com/">Olivier Chafik</a> that <a href="https://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="https://nativelibs4java.googlecode.com/">NativeLibs4Java</a> , <a href="https://rococoa.dev.java.net/">Rococoa</a>, or <a href="https://jna.dev.java.net/">JNA</a>.
 */
public class DiscordUser extends Structure {
	/** C type : DiscordUserId */
	public long id;
	/** C type : char[256] */
	public byte[] username = new byte[256];
	/** C type : char[8] */
	public byte[] discriminator = new byte[8];
	/** C type : char[128] */
	public byte[] avatar = new byte[128];
	public byte bot;
	public DiscordUser() {
		super();
	}
	protected List<String> getFieldOrder() {
		return Arrays.asList("id", "username", "discriminator", "avatar", "bot");
	}
	/**
	 * @param id C type : DiscordUserId<br>
	 * @param username C type : char[256]<br>
	 * @param discriminator C type : char[8]<br>
	 * @param avatar C type : char[128]
	 */
	public DiscordUser(long id, byte username[], byte discriminator[], byte avatar[], byte bot) {
		super();
		this.id = id;
		if ((username.length != this.username.length)) 
			throw new IllegalArgumentException("Wrong array size !");
		this.username = username;
		if ((discriminator.length != this.discriminator.length)) 
			throw new IllegalArgumentException("Wrong array size !");
		this.discriminator = discriminator;
		if ((avatar.length != this.avatar.length)) 
			throw new IllegalArgumentException("Wrong array size !");
		this.avatar = avatar;
		this.bot = bot;
	}
	public DiscordUser(Pointer peer) {
		super(peer);
	}
	public static class ByReference extends DiscordUser implements Structure.ByReference {
		
	};
	public static class ByValue extends DiscordUser implements Structure.ByValue {
		
	};
}
