package discord_game_sdk;
import com.sun.jna.Pointer;
import com.sun.jna.Structure;
import java.util.Arrays;
import java.util.List;
/**
 * <i>native declaration : discord_game_sdk.h:303</i><br>
 * This file was autogenerated by <a href="https://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="https://ochafik.com/">Olivier Chafik</a> that <a href="https://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="https://nativelibs4java.googlecode.com/">NativeLibs4Java</a> , <a href="https://rococoa.dev.java.net/">Rococoa</a>, or <a href="https://jna.dev.java.net/">JNA</a>.
 */
public class DiscordRelationship extends Structure {
	/**
	 * @see EDiscordRelationshipType<br>
	 * C type : EDiscordRelationshipType
	 */
	public int type;
	/** C type : DiscordUser */
	public DiscordUser user;
	/** C type : DiscordPresence */
	public DiscordPresence presence;
	public DiscordRelationship() {
		super();
	}
	protected List<String> getFieldOrder() {
		return Arrays.asList("type", "user", "presence");
	}
	/**
	 * @param type @see EDiscordRelationshipType<br>
	 * C type : EDiscordRelationshipType<br>
	 * @param user C type : DiscordUser<br>
	 * @param presence C type : DiscordPresence
	 */
	public DiscordRelationship(int type, DiscordUser user, DiscordPresence presence) {
		super();
		this.type = type;
		this.user = user;
		this.presence = presence;
	}
	public DiscordRelationship(Pointer peer) {
		super(peer);
	}
	public static class ByReference extends DiscordRelationship implements Structure.ByReference {
		
	};
	public static class ByValue extends DiscordRelationship implements Structure.ByValue {
		
	};
}
