package discord_game_sdk;
import com.sun.jna.Pointer;
import com.sun.jna.Structure;
import java.util.Arrays;
import java.util.List;
/**
 * <i>native declaration : discord_game_sdk.h:333</i><br>
 * This file was autogenerated by <a href="https://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="https://ochafik.com/">Olivier Chafik</a> that <a href="https://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="https://nativelibs4java.googlecode.com/">NativeLibs4Java</a> , <a href="https://rococoa.dev.java.net/">Rococoa</a>, or <a href="https://jna.dev.java.net/">JNA</a>.
 */
public class DiscordFileStat extends Structure {
	/** C type : char[260] */
	public byte[] filename = new byte[260];
	public long size;
	public long last_modified;
	public DiscordFileStat() {
		super();
	}
	protected List<String> getFieldOrder() {
		return Arrays.asList("filename", "size", "last_modified");
	}
	/** @param filename C type : char[260] */
	public DiscordFileStat(byte filename[], long size, long last_modified) {
		super();
		if ((filename.length != this.filename.length)) 
			throw new IllegalArgumentException("Wrong array size !");
		this.filename = filename;
		this.size = size;
		this.last_modified = last_modified;
	}
	public DiscordFileStat(Pointer peer) {
		super(peer);
	}
	public static class ByReference extends DiscordFileStat implements Structure.ByReference {
		
	};
	public static class ByValue extends DiscordFileStat implements Structure.ByValue {
		
	};
}
