package discord_game_sdk;
import com.sun.jna.Pointer;
import com.sun.jna.Structure;
import java.util.Arrays;
import java.util.List;
/**
 * <i>native declaration : discord_game_sdk.h:284</i><br>
 * This file was autogenerated by <a href="https://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="https://ochafik.com/">Olivier Chafik</a> that <a href="https://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="https://nativelibs4java.googlecode.com/">NativeLibs4Java</a> , <a href="https://rococoa.dev.java.net/">Rococoa</a>, or <a href="https://jna.dev.java.net/">JNA</a>.
 */
public class DiscordActivity extends Structure {
	/**
	 * @see EDiscordActivityType<br>
	 * C type : EDiscordActivityType
	 */
	public int type;
	public long application_id;
	/** C type : char[128] */
	public byte[] name = new byte[128];
	/** C type : char[128] */
	public byte[] state = new byte[128];
	/** C type : char[128] */
	public byte[] details = new byte[128];
	/** C type : DiscordActivityTimestamps */
	public DiscordActivityTimestamps timestamps;
	/** C type : DiscordActivityAssets */
	public DiscordActivityAssets assets;
	/** C type : DiscordActivityParty */
	public DiscordActivityParty party;
	/** C type : DiscordActivitySecrets */
	public DiscordActivitySecrets secrets;
	public byte instance;
	public int supported_platforms;
	public DiscordActivity() {
		super();
	}
	protected List<String> getFieldOrder() {
		return Arrays.asList("type", "application_id", "name", "state", "details", "timestamps", "assets", "party", "secrets", "instance", "supported_platforms");
	}
	public DiscordActivity(Pointer peer) {
		super(peer);
	}
	public static class ByReference extends DiscordActivity implements Structure.ByReference {
		
	};
	public static class ByValue extends DiscordActivity implements Structure.ByValue {
		
	};
}
