package discord_game_sdk;
import com.sun.jna.Callback;
import com.sun.jna.Pointer;
import com.sun.jna.Structure;
import java.util.Arrays;
import java.util.List;
/**
 * <i>native declaration : discord_game_sdk.h:612</i><br>
 * This file was autogenerated by <a href="https://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="https://ochafik.com/">Olivier Chafik</a> that <a href="https://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="https://nativelibs4java.googlecode.com/">NativeLibs4Java</a> , <a href="https://rococoa.dev.java.net/">Rococoa</a>, or <a href="https://jna.dev.java.net/">JNA</a>.
 */
public class IDiscordAchievementEvents extends Structure {
	/** C type : on_user_achievement_update_callback* */
	public IDiscordAchievementEvents.on_user_achievement_update_callback on_user_achievement_update;
	/** <i>native declaration : discord_game_sdk.h</i> */
	public interface on_user_achievement_update_callback extends Callback {
		void apply(Pointer event_data, DiscordUserAchievement user_achievement);
	};
	public IDiscordAchievementEvents() {
		super();
	}
	protected List<String> getFieldOrder() {
		return Arrays.asList("on_user_achievement_update");
	}
	/** @param on_user_achievement_update C type : on_user_achievement_update_callback* */
	public IDiscordAchievementEvents(IDiscordAchievementEvents.on_user_achievement_update_callback on_user_achievement_update) {
		super();
		this.on_user_achievement_update = on_user_achievement_update;
	}
	public IDiscordAchievementEvents(Pointer peer) {
		super(peer);
	}
	public static class ByReference extends IDiscordAchievementEvents implements Structure.ByReference {
		
	};
	public static class ByValue extends IDiscordAchievementEvents implements Structure.ByValue {
		
	};
}
