package discord_game_sdk;
import com.sun.jna.Callback;
import com.sun.jna.Pointer;
import com.sun.jna.Structure;
import java.util.Arrays;
import java.util.List;
/**
 * <i>native declaration : discord_game_sdk.h:436</i><br>
 * This file was autogenerated by <a href="https://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="https://ochafik.com/">Olivier Chafik</a> that <a href="https://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="https://nativelibs4java.googlecode.com/">NativeLibs4Java</a> , <a href="https://rococoa.dev.java.net/">Rococoa</a>, or <a href="https://jna.dev.java.net/">JNA</a>.
 */
public class IDiscordRelationshipEvents extends Structure {
	/** C type : on_refresh_callback* */
	public IDiscordRelationshipEvents.on_refresh_callback on_refresh;
	/** C type : on_relationship_update_callback* */
	public IDiscordRelationshipEvents.on_relationship_update_callback on_relationship_update;
	/** <i>native declaration : discord_game_sdk.h</i> */
	public interface on_refresh_callback extends Callback {
		void apply(Pointer event_data);
	};
	/** <i>native declaration : discord_game_sdk.h</i> */
	public interface on_relationship_update_callback extends Callback {
		void apply(Pointer event_data, DiscordRelationship relationship);
	};
	public IDiscordRelationshipEvents() {
		super();
	}
	protected List<String> getFieldOrder() {
		return Arrays.asList("on_refresh", "on_relationship_update");
	}
	/**
	 * @param on_refresh C type : on_refresh_callback*<br>
	 * @param on_relationship_update C type : on_relationship_update_callback*
	 */
	public IDiscordRelationshipEvents(IDiscordRelationshipEvents.on_refresh_callback on_refresh, IDiscordRelationshipEvents.on_relationship_update_callback on_relationship_update) {
		super();
		this.on_refresh = on_refresh;
		this.on_relationship_update = on_relationship_update;
	}
	public IDiscordRelationshipEvents(Pointer peer) {
		super(peer);
	}
	public static class ByReference extends IDiscordRelationshipEvents implements Structure.ByReference {
		
	};
	public static class ByValue extends IDiscordRelationshipEvents implements Structure.ByValue {
		
	};
}
