package discord_game_sdk;
import com.sun.jna.Callback;
import com.sun.jna.Pointer;
import com.sun.jna.Structure;
import com.sun.jna.win32.StdCallLibrary.StdCallCallback;
import java.util.Arrays;
import java.util.List;
/**
 * <i>native declaration : discord_game_sdk.h:392</i><br>
 * This file was autogenerated by <a href="https://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="https://ochafik.com/">Olivier Chafik</a> that <a href="https://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="https://nativelibs4java.googlecode.com/">NativeLibs4Java</a> , <a href="https://rococoa.dev.java.net/">Rococoa</a>, or <a href="https://jna.dev.java.net/">JNA</a>.
 */
public class IDiscordApplicationManager extends Structure {
	/** C type : validate_or_exit_callback* */
	public IDiscordApplicationManager.validate_or_exit_callback validate_or_exit;
	/** C type : get_current_locale_callback* */
	public IDiscordApplicationManager.get_current_locale_callback get_current_locale;
	/** C type : get_current_branch_callback* */
	public IDiscordApplicationManager.get_current_branch_callback get_current_branch;
	/** C type : get_oauth2_token_callback* */
	public IDiscordApplicationManager.get_oauth2_token_callback get_oauth2_token;
	/** C type : get_ticket_callback* */
	public IDiscordApplicationManager.get_ticket_callback get_ticket;
	/** <i>native declaration : discord_game_sdk.h:393</i> */
	public interface validate_or_exit_callback_callback_callback extends Callback {
		void apply(Pointer callback_data, int result);
	};
	/** <i>native declaration : discord_game_sdk.h</i> */
	public interface validate_or_exit_callback extends Callback {
		void apply(IDiscordApplicationManager manager, Pointer callback_data, IDiscordApplicationManager.validate_or_exit_callback_callback_callback callback);
	};
	/** <i>native declaration : discord_game_sdk.h</i> */
	public interface get_current_locale_callback extends Callback {
		void apply(IDiscordApplicationManager manager, Pointer locale);
	};
	/** <i>native declaration : discord_game_sdk.h</i> */
	public interface get_current_branch_callback extends Callback {
		void apply(IDiscordApplicationManager manager, Pointer branch);
	};
	/** <i>native declaration : discord_game_sdk.h:396</i> */
	public interface get_oauth2_token_callback_callback_callback extends Callback {
		void apply(Pointer callback_data, int result, DiscordOAuth2Token oauth2_token);
	};
	/** <i>native declaration : discord_game_sdk.h</i> */
	public interface get_oauth2_token_callback extends Callback {
		void apply(IDiscordApplicationManager manager, Pointer callback_data, IDiscordApplicationManager.get_oauth2_token_callback_callback_callback callback);
	};
	/** <i>native declaration : discord_game_sdk.h:397</i> */
	public interface get_ticket_callback_callback_callback extends Callback {
		void apply(Pointer callback_data, int result, Pointer data);
	};
	/** <i>native declaration : discord_game_sdk.h</i> */
	public interface get_ticket_callback extends Callback {
		void apply(IDiscordApplicationManager manager, Pointer callback_data, IDiscordApplicationManager.get_ticket_callback_callback_callback callback);
	};
	public IDiscordApplicationManager() {
		super();
	}
	protected List<String> getFieldOrder() {
		return Arrays.asList("validate_or_exit", "get_current_locale", "get_current_branch", "get_oauth2_token", "get_ticket");
	}
	/**
	 * @param validate_or_exit C type : validate_or_exit_callback*<br>
	 * @param get_current_locale C type : get_current_locale_callback*<br>
	 * @param get_current_branch C type : get_current_branch_callback*<br>
	 * @param get_oauth2_token C type : get_oauth2_token_callback*<br>
	 * @param get_ticket C type : get_ticket_callback*
	 */
	public IDiscordApplicationManager(IDiscordApplicationManager.validate_or_exit_callback validate_or_exit, IDiscordApplicationManager.get_current_locale_callback get_current_locale, IDiscordApplicationManager.get_current_branch_callback get_current_branch, IDiscordApplicationManager.get_oauth2_token_callback get_oauth2_token, IDiscordApplicationManager.get_ticket_callback get_ticket) {
		super();
		this.validate_or_exit = validate_or_exit;
		this.get_current_locale = get_current_locale;
		this.get_current_branch = get_current_branch;
		this.get_oauth2_token = get_oauth2_token;
		this.get_ticket = get_ticket;
	}
	public IDiscordApplicationManager(Pointer peer) {
		super(peer);
	}
	public static class ByReference extends IDiscordApplicationManager implements Structure.ByReference {
		
	};
	public static class ByValue extends IDiscordApplicationManager implements Structure.ByValue {
		
	};
}
