package discord_game_sdk;
import com.sun.jna.Callback;
import com.sun.jna.Pointer;
import com.sun.jna.Structure;
import java.util.Arrays;
import java.util.List;
/**
 * <i>native declaration : discord_game_sdk.h:535</i><br>
 * This file was autogenerated by <a href="https://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="https://ochafik.com/">Olivier Chafik</a> that <a href="https://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="https://nativelibs4java.googlecode.com/">NativeLibs4Java</a> , <a href="https://rococoa.dev.java.net/">Rococoa</a>, or <a href="https://jna.dev.java.net/">JNA</a>.
 */
public class IDiscordOverlayEvents extends Structure {
	/** C type : on_toggle_callback* */
	public IDiscordOverlayEvents.on_toggle_callback on_toggle;
	/** <i>native declaration : discord_game_sdk.h</i> */
	public interface on_toggle_callback extends Callback {
		void apply(Pointer event_data, byte locked);
	};
	public IDiscordOverlayEvents() {
		super();
	}
	protected List<String> getFieldOrder() {
		return Arrays.asList("on_toggle");
	}
	/** @param on_toggle C type : on_toggle_callback* */
	public IDiscordOverlayEvents(IDiscordOverlayEvents.on_toggle_callback on_toggle) {
		super();
		this.on_toggle = on_toggle;
	}
	public IDiscordOverlayEvents(Pointer peer) {
		super(peer);
	}
	public static class ByReference extends IDiscordOverlayEvents implements Structure.ByReference {
		
	};
	public static class ByValue extends IDiscordOverlayEvents implements Structure.ByValue {
		
	};
}
