package discord_game_sdk;
import com.sun.jna.Callback;
import com.sun.jna.Pointer;
import com.sun.jna.Structure;
import java.util.Arrays;
import java.util.List;
/**
 * <i>native declaration : discord_game_sdk.h:419</i><br>
 * This file was autogenerated by <a href="https://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="https://ochafik.com/">Olivier Chafik</a> that <a href="https://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="https://nativelibs4java.googlecode.com/">NativeLibs4Java</a> , <a href="https://rococoa.dev.java.net/">Rococoa</a>, or <a href="https://jna.dev.java.net/">JNA</a>.
 */
public class IDiscordActivityEvents extends Structure {
	/** C type : on_activity_join_callback* */
	public IDiscordActivityEvents.on_activity_join_callback on_activity_join;
	/** C type : on_activity_spectate_callback* */
	public IDiscordActivityEvents.on_activity_spectate_callback on_activity_spectate;
	/** C type : on_activity_join_request_callback* */
	public IDiscordActivityEvents.on_activity_join_request_callback on_activity_join_request;
	/** C type : on_activity_invite_callback* */
	public IDiscordActivityEvents.on_activity_invite_callback on_activity_invite;
	/** <i>native declaration : discord_game_sdk.h</i> */
	public interface on_activity_join_callback extends Callback {
		void apply(Pointer event_data, Pointer secret);
	};
	/** <i>native declaration : discord_game_sdk.h</i> */
	public interface on_activity_spectate_callback extends Callback {
		void apply(Pointer event_data, Pointer secret);
	};
	/** <i>native declaration : discord_game_sdk.h</i> */
	public interface on_activity_join_request_callback extends Callback {
		void apply(Pointer event_data, DiscordUser user);
	};
	/** <i>native declaration : discord_game_sdk.h</i> */
	public interface on_activity_invite_callback extends Callback {
		void apply(Pointer event_data, int type, DiscordUser user, DiscordActivity activity);
	};
	public IDiscordActivityEvents() {
		super();
	}
	protected List<String> getFieldOrder() {
		return Arrays.asList("on_activity_join", "on_activity_spectate", "on_activity_join_request", "on_activity_invite");
	}
	/**
	 * @param on_activity_join C type : on_activity_join_callback*<br>
	 * @param on_activity_spectate C type : on_activity_spectate_callback*<br>
	 * @param on_activity_join_request C type : on_activity_join_request_callback*<br>
	 * @param on_activity_invite C type : on_activity_invite_callback*
	 */
	public IDiscordActivityEvents(IDiscordActivityEvents.on_activity_join_callback on_activity_join, IDiscordActivityEvents.on_activity_spectate_callback on_activity_spectate, IDiscordActivityEvents.on_activity_join_request_callback on_activity_join_request, IDiscordActivityEvents.on_activity_invite_callback on_activity_invite) {
		super();
		this.on_activity_join = on_activity_join;
		this.on_activity_spectate = on_activity_spectate;
		this.on_activity_join_request = on_activity_join_request;
		this.on_activity_invite = on_activity_invite;
	}
	public IDiscordActivityEvents(Pointer peer) {
		super(peer);
	}
	public static class ByReference extends IDiscordActivityEvents implements Structure.ByReference {
		
	};
	public static class ByValue extends IDiscordActivityEvents implements Structure.ByValue {
		
	};
}
