package discord_game_sdk;
import com.sun.jna.Callback;
import com.sun.jna.Pointer;
import com.sun.jna.Structure;
import java.util.Arrays;
import java.util.List;
/**
 * <i>native declaration : discord_game_sdk.h:577</i><br>
 * This file was autogenerated by <a href="https://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="https://ochafik.com/">Olivier Chafik</a> that <a href="https://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="https://nativelibs4java.googlecode.com/">NativeLibs4Java</a> , <a href="https://rococoa.dev.java.net/">Rococoa</a>, or <a href="https://jna.dev.java.net/">JNA</a>.
 */
public class IDiscordStoreEvents extends Structure {
	/** C type : on_entitlement_create_callback* */
	public IDiscordStoreEvents.on_entitlement_create_callback on_entitlement_create;
	/** C type : on_entitlement_delete_callback* */
	public IDiscordStoreEvents.on_entitlement_delete_callback on_entitlement_delete;
	/** <i>native declaration : discord_game_sdk.h</i> */
	public interface on_entitlement_create_callback extends Callback {
		void apply(Pointer event_data, DiscordEntitlement entitlement);
	};
	/** <i>native declaration : discord_game_sdk.h</i> */
	public interface on_entitlement_delete_callback extends Callback {
		void apply(Pointer event_data, DiscordEntitlement entitlement);
	};
	public IDiscordStoreEvents() {
		super();
	}
	protected List<String> getFieldOrder() {
		return Arrays.asList("on_entitlement_create", "on_entitlement_delete");
	}
	/**
	 * @param on_entitlement_create C type : on_entitlement_create_callback*<br>
	 * @param on_entitlement_delete C type : on_entitlement_delete_callback*
	 */
	public IDiscordStoreEvents(IDiscordStoreEvents.on_entitlement_create_callback on_entitlement_create, IDiscordStoreEvents.on_entitlement_delete_callback on_entitlement_delete) {
		super();
		this.on_entitlement_create = on_entitlement_create;
		this.on_entitlement_delete = on_entitlement_delete;
	}
	public IDiscordStoreEvents(Pointer peer) {
		super(peer);
	}
	public static class ByReference extends IDiscordStoreEvents implements Structure.ByReference {
		
	};
	public static class ByValue extends IDiscordStoreEvents implements Structure.ByValue {
		
	};
}
