package discord_game_sdk;
import com.sun.jna.Callback;
import com.sun.jna.Pointer;
import com.sun.jna.Structure;
import com.sun.jna.win32.StdCallLibrary.StdCallCallback;
import java.util.Arrays;
import java.util.List;
/**
 * <i>native declaration : discord_game_sdk.h:413</i><br>
 * This file was autogenerated by <a href="https://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="https://ochafik.com/">Olivier Chafik</a> that <a href="https://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="https://nativelibs4java.googlecode.com/">NativeLibs4Java</a> , <a href="https://rococoa.dev.java.net/">Rococoa</a>, or <a href="https://jna.dev.java.net/">JNA</a>.
 */
public class IDiscordImageManager extends Structure {
	/** C type : fetch_callback* */
	public IDiscordImageManager.fetch_callback fetch;
	/** C type : get_dimensions_callback* */
	public IDiscordImageManager.get_dimensions_callback get_dimensions;
	/** C type : get_data_callback* */
	public IDiscordImageManager.get_data_callback get_data;
	/** <i>native declaration : discord_game_sdk.h:414</i> */
	public interface fetch_callback_callback_callback extends StdCallCallback {
		void apply(Pointer callback_data, int result, discord_game_sdk.DiscordImageHandle.ByValue handle_result);
	};
	/** <i>native declaration : discord_game_sdk.h</i> */
	public interface fetch_callback extends Callback {
		void apply(IDiscordImageManager manager, discord_game_sdk.DiscordImageHandle.ByValue handle, byte refresh, Pointer callback_data, IDiscordImageManager.fetch_callback_callback_callback callback);
	};
	/** <i>native declaration : discord_game_sdk.h</i> */
	public interface get_dimensions_callback extends Callback {
		int apply(IDiscordImageManager manager, discord_game_sdk.DiscordImageHandle.ByValue handle, DiscordImageDimensions dimensions);
	};
	/** <i>native declaration : discord_game_sdk.h</i> */
	public interface get_data_callback extends Callback {
		int apply(IDiscordImageManager manager, discord_game_sdk.DiscordImageHandle.ByValue handle, Pointer data, int data_length);
	};
	public IDiscordImageManager() {
		super();
	}
	protected List<String> getFieldOrder() {
		return Arrays.asList("fetch", "get_dimensions", "get_data");
	}
	/**
	 * @param fetch C type : fetch_callback*<br>
	 * @param get_dimensions C type : get_dimensions_callback*<br>
	 * @param get_data C type : get_data_callback*
	 */
	public IDiscordImageManager(IDiscordImageManager.fetch_callback fetch, IDiscordImageManager.get_dimensions_callback get_dimensions, IDiscordImageManager.get_data_callback get_data) {
		super();
		this.fetch = fetch;
		this.get_dimensions = get_dimensions;
		this.get_data = get_data;
	}
	public IDiscordImageManager(Pointer peer) {
		super(peer);
	}
	public static class ByReference extends IDiscordImageManager implements Structure.ByReference {
		
	};
	public static class ByValue extends IDiscordImageManager implements Structure.ByValue {
		
	};
}
