grpc:
  host: localhost
  port: 50051
  tls:
    enabled: false
    truststore:
      file: C:\Users\Example\Desktop\VisualBukkit-Certs.p12
      password: password
    client-auth:
      enabled: false
      keystore:
        file: C:\Users\Example\Desktop\VisualBukkit-Plugin-Private.p12
        password: password
      key:
        password: password