name: VisualBukkit
version: ${project.version}
api-version: 1.20
main: com.gmail.visualbukkit.plugin.VisualBukkitPlugin

commands:
  visualbukkit:
    aliases: [vb]
    description: The main Visual Bukkit command
    permission: vb.command

permissions:
  vb.command:
    description: Gives access to /visualbukkit
    default: op